---
title: "Global Terrorism Analysis (1970 - 2017)"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
    orientation: rows
runtime: shiny
---

```{r setup, include=FALSE}
library(flexdashboard)
library(tidyr)
library(dplyr)
library(maps)
library(ggmap)
library(shiny)
library(plotly)
```

```{r}
#source files
source ('./functions/dataImport.R', local = T)
source ('./functions/attacksOverYears.R', local = T)
source ('./functions/casualtiesOverYears.R', local = T)
source ('./functions/highCasualtyFactor.R', local = T)
source('./functions/mostAttackedCountries.R', local = T)
source('./functions/visualizeCountMap.R', local = T)
```

```{r}
terr <- dataImport()
world <- map_data("world")
```

```{r results='hide'}
#for UTF-8 encoding
Sys.setlocale('LC_ALL','C')
```




General Figures
=======================================================================

Sidebar {.sidebar}
-----------------------------------------------------------------------

#### **Common Filters**
```{r}
#options for attack logistics
attackLogistics <- c('International', 'Domestic', 'All')

#targets drop down input for map
selectInput('selectLogistic', 'Logistic of Attack',
            choices = attackLogistics,
            selected = 'All')
```


#### **Filters for map** 
```{r}
# year slider input for reactive map
sliderInput('yearRange', 'Years of attacks',
            min = min(terr$year), max = max(terr$year),
            value = c(min(terr$year), max(terr$year)),
            step = 1, sep = "")

#options for attack types
weapons <- terr %>%
  distinct(weapon)

#weapons drop down input for map
selectInput('selectWeapon', 'Weapon used for attack',
            choices = c(weapons,'All'),
            selected = 'All')

#options for target type
targets <- terr %>%
  distinct(target)

#targets drop down input for map
selectInput('selectTarget', 'Main target',
            choices = c(targets, 'All'),
            selected = 'All')
```

#### **Filters for trends** 
```{r}
#options for countries drop down
nationNames <- terr %>%
  distinct(nation)
  
#country drop down input for yearly trend
selectInput('selectCountry', 'Country where attack occured',
            choices = c(nationNames,'All'),
            selected = 'All')

#options for group drop down
groups <- terr %>%
  distinct(gname)

#group drop down input for yearly trend
selectInput('selectGroup', 'Terrorist group responsible',
            choices = c(groups, 'All'),
            selected = 'All')
```

Row
-----------------------------------------------------------------------

### Years of data

```{r}
years <- terr$year %>%
  max() -
terr$year %>%
  min() + 1

valueBox(years, icon = "ion-calendar")
```

### Total Attacks

```{r}
terr %>%
  summarise(n()) %>%
  valueBox(icon = "ion-nuclear", color = 'orange')
```

### Total Casualties

```{r}
terr %>%
  summarise(sum(casualties)) %>%
  valueBox(icon = "ion-people", color = 'red')
```

Row {.tabset}
-----------------------------------------------------------------------

### **Attacks around the world**

```{r}
#startYear <- reactive(as.integer(input$yearRange[1]))
#endYear <- reactive(as.integer(input$yearRange[2]))

renderPlotly({
  graph <- terr %>%
    {if (input$selectWeapon != 'All') 
      filter(., weapon == input$selectWeapon)
      else
        .} %>%
    {if (input$selectTarget != 'All')
      filter(., target == input$selectTarget)
      else
        .} %>%
    {if (input$selectLogistic != 'All')
      if (input$selectLogistic == 'International')
        filter(., INT_ANY == '1')
        else
          filter(., INT_ANY == '0')
      else
        .} %>%
    filter(year >= input$yearRange[1], 
           year <= input$yearRange[2]) %>%
    group_by(nation) %>%
    summarise(Total=n()) %>%
    visualizeCountMap(world, "Number of terrorist attacks around the world") 
    
  ggplotly(graph)})
```

### **Casualties around the world**

```{r}
renderPlotly({
  graph <- terr %>%
    {if (input$selectWeapon != 'All') 
      filter(., weapon == input$selectWeapon)
      else
      .} %>%
    {if (input$selectTarget != 'All') 
      filter(., target == input$selectTarget)
      else
        .} %>%
    {if (input$selectLogistic != 'All')
      if (input$selectLogistic == 'International')
        filter(., INT_ANY == '1')
        else
          filter(., INT_ANY == '0')
      else
        .} %>%
    filter(year >= input$yearRange[1], 
           year <= input$yearRange[2]) %>%
    group_by(nation) %>%
    summarise(Total = sum(casualties)) %>%
    visualizeCountMap(world, "Number of Casualties around the world")
  
  ggplotly(graph)})
```

Row {.tabset}
-----------------------------------------------------------------------

### **Attacks over the years**

```{r}
renderPlotly({
  #select All for all countries
  graph <- terr %>%
    {if (input$selectCountry != 'All') 
      filter(., nation == input$selectCountry)
      else
        .}%>%
    {if (input$selectGroup != 'All') 
      filter(., gname == input$selectGroup)
      else
        .} %>%
    {if (input$selectLogistic != 'All')
      if (input$selectLogistic == 'International')
        filter(., INT_ANY == '1')
        else
          filter(., INT_ANY == '0')
      else
        .} %>%
    attacksOverYears(xstart = min(terr$year), xend = max(terr$year))
  
  ggplotly(graph)})
```

### **Casualties over the years**

```{r}
renderPlotly({
  graph <- terr %>%
    {if (input$selectCountry != 'All') 
      filter(., nation == input$selectCountry)
      else
        .} %>%
    {if (input$selectGroup != 'All') 
      filter(., gname == input$selectGroup)
      else
        .} %>%
    {if (input$selectLogistic != 'All')
      if (input$selectLogistic == 'International')
        filter(., INT_ANY == '1')
        else
          filter(., INT_ANY == '0')
      else
        .} %>%
    casualtiesOverYears(xstart = min(terr$year), xend = max(terr$year))
    
  ggplotly(graph)})
```

### Corresponsing Data - filler for corresponding data

```{r}
#renderTable({
#  terr %>%
#    filter(nation == input$selectCountry)
#})
```

Row
-----------------------------------------------------------------------
Source: National Consortium for the Study of Terrorism and Responses to Terrorism (START). (2018). Global Terrorism Database [Data file]. Retrieved from https://www.start.umd.edu/gtd

Factors
=======================================================================

Row
-----------------------------------------------------------------------

### Most Used Weapon

```{r}
terr %>%
  group_by(weapon) %>%
  summarise(n()) %>%
  top_n(1) %>%
  pull('weapon') %>%
  valueBox(icon = "ion-nuclear")
```

### Most Active Group

```{r}
terr %>%
  filter(gname != 'Unknown') %>%
  group_by(gname) %>%
  summarise(n()) %>%
  top_n(1) %>%
  pull('gname') %>%
  valueBox(icon = 'ion-people')
```

Sidebar {.sidebar}
-----------------------------------------------------------------------
```{r}
numericInput('xaxisTicks', 'How many values to show on x-axis?', 10,
             5, 100, 1)


```


Row {.tabset}
-----------------------------------------------------------------------

### **High Casualty Attacks**

```{r}
renderPlotly({
  graph <- terr[c('target1', 'casualties')] %>%
    top_n(input$xaxisTicks, casualties) %>% 
    mutate(target1 = forcats::fct_reorder(target1, -casualties)) %>%
    highCasualtyFactor('target1', 'casualties', 
                     xlab = 'Attack Target', ylab = 'Casualty Count')})
```

### **High Casualty Terrorist Groups**

```{r}
renderPlotly(({
  graph <- terr[c('gname', 'casualties')]%>%
    filter(gname!='Unknown') %>%
    group_by(gname) %>%
    summarise(casualties=n()) %>%
    top_n(input$xaxisTicks, casualties) %>%
    mutate(gname = forcats::fct_reorder(gname, -casualties)) %>%
    highCasualtyFactor('gname', 'casualties', 
                     xlab = 'Terrorist Group', ylab = 'Casualty Count')}))
```

### **Most Attacked Countries**

```{r}
renderPlotly({
  graph <- terr['nation'] %>%
    group_by(nation) %>%
    summarise(Total=n()) %>%
    top_n(input$xaxisTicks, Total) %>%
    mutate(nation = forcats::fct_reorder(nation, -Total)) %>%
    highCasualtyFactor('nation', 'Total', 
                       xlab = 'Country', ylab = 'Attacks Count')})
```



